name: electron
version: 0.0.3+1
description: Electron wrapper for dart
author: electron.dart
homepage: https://github.com/electron-dart/electron.dart

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  nodejs:
    git: https://github.com/electron-dart/nodejs.dart.git
  js: '>=0.6.0 <0.7.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
